# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-27 07:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback', models.CharField(max_length=128, verbose_name='Callback')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[(b'pending', b'Pending'), (b'process', b'Process'), (b'success', b'Success'), (b'failure', b'Failure')], default=b'pending', max_length=128, verbose_name='\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435')),
                ('message', models.TextField(blank=True, null=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_log_source', to='broker.Source', verbose_name='\u041f\u0440\u0438\u0435\u043c\u043d\u0438\u043a')),
            ],
        ),
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=128, verbose_name='\u0421\u0438\u0433\u043d\u0430\u0442\u0443\u0440\u0430')),
                ('args_signal', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('kwargs_signal', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_log_source', to='broker.Source', verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a')),
            ],
        ),
        migrations.AddField(
            model_name='callbacklog',
            name='signal_logger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_logger', to='logger.SignalLog', verbose_name='\u041b\u043e\u0433 \u0441\u043e\u0431\u044b\u0442\u0438\u044f'),
        ),
    ]
