# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-26 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbacklog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 26, 12, 51, 13, 426071, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callbacklog',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 12, 26, 12, 51, 19, 241967, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
    ]
