# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-30 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbacklog',
            name='uuid_task',
            field=models.UUIDField(blank=True, null=True, verbose_name='Uuid \u0442\u0430\u0441\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='callbacklog',
            name='callback',
            field=models.CharField(max_length=128, verbose_name='\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0447\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='callbacklog',
            name='state',
            field=models.CharField(choices=[(b'pending', '\u0412 \u043e\u0436\u0438\u0434\u0430\u043d\u0438\u0438'), (b'process', '\u0412\u044b\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f'), (b'success', '\u0423\u0441\u043f\u0435\u0448\u043d\u043e \u0437\u0430\u0432\u0435\u0440\u0448\u0451\u043d'), (b'failure', '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d \u0441 \u043e\u0448\u0438\u0431\u043a\u043e\u0439')], default=b'pending', max_length=128, verbose_name='\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435'),
        ),
    ]
