# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-30 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20161230_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callbacklog',
            old_name='uuid_task',
            new_name='task_uuid',
        ),
    ]
