# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-30 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20161230_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbacklog',
            name='check_task_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Uuid \u0442\u0430\u0441\u043a\u0430 \u043e\u0442\u043c\u0435\u043d\u044b'),
        ),
    ]
