# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 05:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_auto_20170112_0823'),
        ('logger', '0004_callbacklog_check_task_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackLogHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback', models.CharField(max_length=128, verbose_name='\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0447\u0438\u043a')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[(b'pending', '\u0412 \u043e\u0436\u0438\u0434\u0430\u043d\u0438\u0438'), (b'process', '\u0412\u044b\u043f\u043e\u043b\u043d\u044f\u0435\u0442\u0441\u044f'), (b'success', '\u0423\u0441\u043f\u0435\u0448\u043d\u043e \u0437\u0430\u0432\u0435\u0440\u0448\u0451\u043d'), (b'failure', '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d \u0441 \u043e\u0448\u0438\u0431\u043a\u043e\u0439')], default=b'pending', max_length=128, verbose_name='\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435')),
                ('message', models.TextField(blank=True, null=True, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('task_uuid', models.UUIDField(blank=True, null=True, verbose_name='Uuid \u0442\u0430\u0441\u043a\u0430')),
                ('check_task_uuid', models.UUIDField(blank=True, null=True, verbose_name='Uuid \u0442\u0430\u0441\u043a\u0430 \u043e\u0442\u043c\u0435\u043d\u044b')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('created', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logger_callbackloghistory_destination', to='broker.Source', verbose_name='\u041f\u0440\u0438\u0435\u043c\u043d\u0438\u043a')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalLogHistory',
            fields=[
                ('signature', models.CharField(max_length=128, verbose_name='\u0421\u0438\u0433\u043d\u0430\u0442\u0443\u0440\u0430')),
                ('args_signal', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('kwargs_signal', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logger_signalloghistory_source', to='broker.Source', verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='signallog',
            old_name='date_create',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='callbacklog',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logger_callbacklog_destination', to='broker.Source', verbose_name='\u041f\u0440\u0438\u0435\u043c\u043d\u0438\u043a'),
        ),
        migrations.AlterField(
            model_name='signallog',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logger_signallog_source', to='broker.Source', verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='callbackloghistory',
            name='signal_logger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_logger', to='logger.SignalLogHistory', verbose_name='\u041b\u043e\u0433 \u0441\u043e\u0431\u044b\u0442\u0438\u044f'),
        ),
    ]
