# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-15 06:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128, verbose_name='\u0422\u0438\u043f \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0430')),
                ('init_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=b'{}', null=True)),
            ],
        ),
    ]
