# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-27 07:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(blank=True, max_length=128, verbose_name='\u0421\u0438\u0433\u043d\u0430\u043b')),
                ('callback', models.CharField(blank=True, max_length=128, verbose_name='Callback')),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128, verbose_name='\u0422\u0438\u043f \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0430')),
                ('init_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_destination', to='broker.Source', verbose_name='\u041f\u0440\u0438\u0435\u043c\u043d\u0438\u043a'),
        ),
        migrations.AddField(
            model_name='rule',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_source', to='broker.Source', verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a'),
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together=set([('source', 'destination', 'signal', 'callback')]),
        ),
    ]
