# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-14 12:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128, verbose_name=b'\xd0\xa2\xd0\xb8\xd0\xbf \xd0\xb8\xd1\x81\xd1\x82\xd0\xbe\xd1\x87\xd0\xbd\xd0\xb8\xd0\xba\xd0\xb0')),
                ('init_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=b'{}', null=True)),
            ],
        ),
    ]
