# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-19 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(blank=True, max_length=128, verbose_name='\u0421\u0438\u0433\u043d\u0430\u043b')),
                ('callback', models.CharField(blank=True, max_length=128, verbose_name='Callback')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_destination', to='broker.Source', verbose_name='\u041f\u0440\u0438\u0435\u043c\u043d\u0438\u043a')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_source', to='broker.Source', verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together=set([('source', 'destination', 'signal', 'callback')]),
        ),
    ]
