# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-30 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='callback',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0447\u0438\u043a'),
        ),
    ]
