# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_auto_20161230_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='type_source',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u0422\u0438\u043f \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.CharField(max_length=128, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0430'),
        ),
    ]
