# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-23 12:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_auto_20161219_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=128, verbose_name='\u0421\u0438\u0433\u043d\u0430\u0442\u0443\u0440\u0430')),
                ('args_signal', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=b'[]', null=True)),
                ('kwargs_signal', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=b'{}', null=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=b'{}', null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_log_source', to='broker.Source', verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a')),
            ],
        ),
    ]
