# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-08 05:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_auto_20170112_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='additional_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0435 \u043f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b \u0432\u044b\u0437\u043e\u0432\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u0447\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='source',
            name='init_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440\u044b \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0430'),
        ),
    ]
